### ISSUE TITLE
As an OC support user I want be able to filter by unique X-Request-ID header so I can tracing requests in apache and owncloud logs

### ISSUE THREAD

**Issue by nasli** [owncloud/ios-sdk#1]
As @butonic suggested https://github.com/owncloud/ios/issues/950

https://github.com/owncloud/core/pull/28144 has been merged. It will use the value of a `X-Request-ID` header as the request id in log files to allow linking events on the client to events in the apache and owncloud logs.

AC:

- Generate a string to use as unique id.
  - 20-200 chars
  - only `[a-zA-Z0-9-+/_=.:]` allowed
- Use it in the client log
- Send it as `X-Request-ID` header on every request

_____

Tasks 

- [ ] [GIT] Create branch
- [ ] [DEV] ...
- [ ] [DEV] ...
- [ ] [QA] ... 
- [ ] [GIT] Merge branch

**Comment by felix-schwarz** [comment]
This should be pretty easy to add.

Should every request ID be unique?
Or should it be built from the combination of a [client-ID] + [random string for every request]?

**Comment by michaelstingl** [comment]
I'd say random string only. User agent is already available in the header of http request. @butonic for more input?

This is the related issue for the desktop client: https://github.com/owncloud/client/issues/5853 (commit: https://github.com/owncloud/client/commit/1fb68e8711e7efa194cf5cd4c915b025e9572038)

**Comment by butonic** [comment]
all request ids must be unique. uuid v5 is fine. uuid v1 would leak the mac / allow tracking the client.

**Comment by felix-schwarz** [comment]
This is implemented as of https://github.com/owncloud/ios-sdk/commit/6534f982423addff0ba279bf87cf019c6731ca3e.
