### ISSUE TITLE
Introduce OCConnectionRequestMethodREPORT to apply oc:filter-rules on DAV requests

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/ios-sdk#14]
See description for the `REPORT` method on https://tools.ietf.org/html/rfc3253#section-3.6

> Unlike a resource property, which has a single value, **the value of a report can depend on additional information specified in the REPORT request body** and in the REPORT request headers.

Some examples we have in ownCloud for this kind of "additional information" are:

### Fetch all the user favorites:

```xml
<oc:filter-files  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
    <d:prop>
        <!-- the properties you want to include on the REPORT -->
    </d:prop>
    <oc:filter-rules>
        <oc:favorite>1</oc:favorite>
    </oc:filter-rules>
</oc:filter-files>
```

### Get the files tagged with a [Collaborative Tag](https://doc.owncloud.org/server/10.0/user_manual/files/webgui/tagging.html):

Replace the content of `oc:filter-rules` above with:

```xml
<oc:systemtag>{{ID of the collaborative tag}}</oc:systemtag>
```

In the future, `REPORT` might also be adopted for search (ref. https://github.com/owncloud/core/issues/25373)

---

There's some documentation for this on https://github.com/owncloud/documentation/issues/2950 (specially everything rel. to pagination)

**Comment by SamuAlfageme** [comment]
Update: https://github.com/owncloud/core/issues/25373#issuecomment-397977105

![it's happening](https://media.giphy.com/media/rl0FOxdz7CcxO/giphy.gif)

**Comment by felix-schwarz** [comment]
This is implemented by the SDK at the time of writing.
