### ISSUE TITLE
Additional node properties on OCItem

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/ios-sdk#15]
I was looking at how `OCXMLParserNode` works (to evaluate the effort to integrate favorites) and noticed a couple of interesting DAV node properties missing from `OCItem`'s model: 

- [ ] `oc:favorite`
- [ ] `oc:privatelink` -> see https://github.com/owncloud/core/pull/29021
- [ ] `oc:checksums` 

### For Shares: 

- [ ] OCS' `share-permissions` - coming from [`lib/public/constants.php`](https://github.com/owncloud/core/blob/master/lib/public/Constants.php) (e.g. "can edit"...) 
- [ ] `oc:owner-id`
- [ ] `oc:owner-display-name`

**Comment by felix-schwarz** [comment]
Closing this issue:

> * [ ]  `oc:favorite`

Supported in the `master` branch of the `ios-sdk` by now.

> * [ ]  `oc:privatelink` -> see [owncloud/core#29021](https://github.com/owncloud/core/pull/29021)

This does not seem relevant to the iOS client at this time.

> * [ ]  `oc:checksums`

Will be used in the future to verify downloads for which this information is not provided immediately, so only files whose checksums match after completing the download are actually accepted.

> ### For Shares:
> * [ ]  OCS' `share-permissions` - coming from [`lib/public/constants.php`](https://github.com/owncloud/core/blob/master/lib/public/Constants.php) (e.g. "can edit"...)

As far as I can see, the same information is provided by the Share API and is therefore also available through the `OCShare` objects provided by the SDK.

> * [ ]  `oc:owner-id`
> * [ ]  `oc:owner-display-name`

Added `oc:owner-id` in the `develop` branch yesterday and, combined with the previous `oc:owner-display-name` property, made it available as a proper `OCUser` instance as `OCItem.owner`.
