### ISSUE TITLE
Thumbnail persist between extension or MiME type changes

### ISSUE THREAD

**Issue by pablocarmu** [owncloud/ios-sdk#26]
When you change one file extension to another and then, you ask for the new thumbnail with the same thumbnail size that you requested before, the SDK returns the previously cached thumbnail for this size. This lead to misleading UI.

Maybe the SDK should be aware of the extension or MIME type changes and then delete all its thumbnails, or at least request new ones and compare.

**Comment by felix-schwarz** [comment]
This has been resolved with 60d7d43b8a2a8fed22696332385c811e09a9e616.
