### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-sdk#3]
This issue aims to be an epic related with the authentication development of the SDK. Also opened to discussion, of course. A first approach to a way in collaborative work. 

I'll add some generic tasks to be developed, that can be splitted in different issues (that would be awesome!!). Please, all the stuff you miss/think it is not valuable/improvable, do not hesitate to comment.

- [x] Connection handling
- [x] Creation of a bookmark (OAuth2 / basic)
- [x] Edition of a bookmark (OAuth2 / basic)
- [x] Removal of a bookmark (OAuth2 / basic)
- [x] Certificate handling (http/https secured/https self-signed or 
- [x] Multitenacy servers
- [x] Redirected servers (301)
- [x] Redirected servers (302)
- [ ] SAML servers

**Comment by felix-schwarz** [comment]
Closing this issue since all currently planned features on the list have been implemented. Let's put SAML into an issue of its own in case we decide to also support it in the future.
