### ISSUE TITLE
Blanks in username causes 404 in PROPFIND

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-sdk#33]
Username that contain blanks causes 404 responses in PROPFINDS, leading to empty folder navigation. 

Same issue happened in Android client (https://github.com/owncloud/android/issues/2347). The fix developed by @davigonz solved the problem but caused another one related with '@' character. All of them causing by the way the core SabreDAV handles with encoding

Discussion related in core repo: https://github.com/owncloud/core/issues/33594

A double decode in client side should fix the problem.

**Comment by davigonz** [comment]
> A double decode in client side should fix the problem.

Here you have the commit in our library that fixes the problem => https://github.com/owncloud/android-library/pull/216/commits/b52306274012fc2db51484924d919dd02329e120
