### ISSUE TITLE
Object for User info 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-sdk#4]
I miss in the SDK, some class or specification related with the user. Currently we are handling users taking in account that they have some different features to handle:

- Username
- Display name
- Avatar
- Maybe others (not mandatory) that some kind of servers LDAP or AD support

so, it is worthy to handle separately.

Could you take care @pablocarmu @nasli?

CC @felix-schwarz

**Comment by felix-schwarz** [comment]
Good point!

I've added OCUser with the latest push and modified OCShare to use it.

Right now it covers:
- Username
- Display name
- Avatar Image Data

**Comment by jesmrec** [comment]
> is there an endpoint to fetch a list of all users of a server?

No, afaik. Which use case is this one useful for? 

> how are users from other servers referenced that share a folder with the user's server?

The current app does not show the identity of the sharing user. You see shared content, but not who shares. 

In the other direction, `username@server` to reference other server's users to share with. 

> is there any persistent, unique identifier for each user that's not the user name, display name, etc.?
where to fetch the avatar image for a user? (we talked about this in the call, but also adding it here to keep track of it)

I have to research about the new way to retrieve this info. The legacy one is a GET authenticated request against `<URL>/index.php/avatar/<username>` . This is a "fake" endpoint. It is like a shortcut URL to get the avatar.

**Comment by felix-schwarz** [comment]
> > is there an endpoint to fetch a list of all users of a server?
> 
> No, afaik. Which use case is this one useful for? 

This could be useful for picking local users to share with from a list - or to support auto-completion.

> > how are users from other servers referenced that share a folder with the user's server?
> 
> The current app does not show the identity of the sharing user. You see shared content, but not who shares. 
> 
> In the other direction, `username@server` to reference other server's users to share with. 

Thanks.

Would this go into `userName`?
Or could the `username@server` pattern conflict with other possible contents in that property?
Is looking for `username@server` a reliable way to determine if this is a user on a different server?

> > is there any persistent, unique identifier for each user that's not the user name, display name, etc.?
> where to fetch the avatar image for a user? (we talked about this in the call, but also adding it here to keep track of it)
> 
> I have to research about the new way to retrieve this info. The legacy one is a GET authenticated request against `<URL>/index.php/avatar/<username>` . This is a "fake" endpoint. It is like a shortcut URL to get the avatar. 

Thanks in advance!

**Comment by SamuAlfageme** [comment]
> is there an endpoint to fetch a list of all users of a server?
> This could be useful for picking local users to share with from a list - or to support auto-completion.

You might want to check the OCS Recipient API for this: https://doc.owncloud.org/server/latest/developer_manual/core/ocs-recipient-api.html (i.e. the mechanism used by the webUI to autocomplete for private shares. ref. https://github.com/owncloud/core/issues/18117) - there's currently no way to list "all users" 

- e.g. to search all users containing "`d`" on the username: 

```bash
curl '<server>/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=d&perPage=200&itemType=file' \
    -H 'OCS-APIREQUEST: true' \
    [...]
```

That returns 2 users and one group: 

```json
{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":100,
         "message":"OK",
         "totalitems":"",
         "itemsperpage":""
      },
      "data":{
         "exact":{
            "users":[

            ],
            "groups":[

            ],
            "remotes":[

            ]
         },
         "users":[
            {
               "label":"admin",
               "value":{
                  "shareType":0,
                  "shareWith":"admin"
               }
            },
            {
               "label":"demo",
               "value":{
                  "shareType":0,
                  "shareWith":"demo"
               }
            }
         ],
         "groups":[
            {
               "label":"admin",
               "value":{
                  "shareType":1,
                  "shareWith":"admin"
               }
            }
         ],
         "remotes":[

         ]
      }
   }
}
```

> how are users from other servers referenced that share a folder with the user's server?

- You might find the remote user that initiated the share on the federated share notification:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/36664625-863b6530-1ae5-11e8-877b-7213b028368e.png"/>
</p>

```json
{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":200,
         "message":null,
         "totalitems":"",
         "itemsperpage":""
      },
      "data":[
         {
            "notification_id":13,
            "app":"files_sharing",
            "user":"samuel",
            "datetime":"2018-02-26T10:46:24+00:00",
            "object_type":"remote_share",
            "object_id":"56",
            "subject":"You received \"\/ownCloud Manual.pdf\" as a remote share from admin@https:\/\/demo.owncloud.org\/",
            "message":"",
            "link":"",
            "actions":[
               {
                  "label":"Decline",
                  "link":"https:\/\/<server>\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/pending\/56",
                  "type":"DELETE",
                  "primary":false
               },
               {
                  "label":"Accept",
                  "link":"https:\/\/<server>\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/pending\/56",
                  "type":"POST",
                  "primary":true
               }
            ],
            "icon":""
         }
      ]
   }
}
```

> is there any persistent, unique identifier for each user that's not the user name, display name, etc.?

- This is a hot topic that caused us headaches with migrations from Basic-auth accounts to OAuth schemes (ref. https://github.com/owncloud/oauth2/issues/109#issuecomment-357663934) - Generally speaking, the `user_id` will be the unique identifier you can use to reference any internal user from the account table. The [user provisioning API](https://doc.owncloud.org/server/latest/admin_manual/configuration/user/user_provisioning_api.html) can be used to find out this id: 

```bash
curl -X GET 'https://demo.owncloud.org/ocs/v1.php/cloud/user?format=json' \
    -H 'OCS-APIREQUEST: true' \
    [...]
```

returns:

```json
{
    "ocs": {
        "meta": {
            "status": "ok",
            "statuscode": 100,
            "message": "OK",
            "totalitems": "",
            "itemsperpage": ""
        },
        "data": {
            "id": "demo",
            "display-name": "demo",
            "email": null
        }
    }
}
```

Also, notice this `user_id` will be used for the fully-qualified DAV path: `remote.php/dav/files/<user_id>`. Users coming from an LDAP backend deserve special care as they might be `user_id`'d with an [RFC4122](https://tools.ietf.org/html/rfc4122)-compliant UUID. (see e.g. https://github.com/owncloud/core/issues/23412 for some collaterals this have). 

> where to fetch the avatar image for a user? 

- New DAV resource to retrieve avatars: https://github.com/owncloud/core/pull/26872
    - Old endpoint decomission request: https://github.com/owncloud/core/issues/30062

**Comment by jesmrec** [comment]
Is this already completely done? 

in that case, we can close.

**Comment by felix-schwarz** [comment]
@jesmrec There is already some usage of this class in the SDK now, but I'd like to keep it open as a point of reference (+ to keep the info in one place) until all features using it have been implemented.

**Comment by felix-schwarz** [comment]
The implementation of sharing - and with it the implementation of `OCUser`, `OCGroup` and `OCRecipient` - is done at the time of writing.
