### ISSUE TITLE
Server capabilities

### ISSUE THREAD

**Issue by pablocarmu** [owncloud/ios-sdk#5]
A ownCloud server has a list of capabilities. This capabilities covers from shares permissions, file chunking, file versioning and more. Even ownCloud marketplace apps can add it’s own capabilities to the server.

It could be interesting to have this covered in the SDK.
e.g.  an app that uses the SDK could choose to show or not in the UI the _share_ button depending of the server share capabilities. Or the SDK itself could choose between chunking the uploads if the server support it.

This is the documentation for the capabilities API endpoint:
https://doc.owncloud.org/server/10.0/developer_manual/core/ocs-capabilities.html

Here are also some of the php files from Core repository that specifies the capabilities:
[File sharing](https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Capabilities.php)
[Files](https://github.com/owncloud/core/blob/master/apps/files/lib/Capabilities.php)

And the Objective-C header to define capabilities that the current library is using:
[OCCapabilities.h](https://github.com/owncloud/ios-library/blob/master/OCCommunicationLib/OCCommunicationLib/OCCapabilities.h)

What do you think @felix-schwarz ?

**Comment by felix-schwarz** [comment]
The SDK covers capabilities by now.
