### ISSUE TITLE
Crash when opening Favorites in iOS-App

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-sdk#51]
iOS-App will crash, if the Favorites view is opened, right after a bookmark (with a large file list) is opened
### Steps to reproduce
1. Add a new bookmark
2. Immediately open `Quick Access`, `Favorites`
3. Crash

### Expected behaviour
Favorites view will open without a crash

### Actual behaviour
App will crash

### Client
**iOS version:**
12.3

**ownCloud app version:**
1.0.1 (124) Release App Store

**Comment by felix-schwarz** [comment]
Closing this issue as it has been addressed at the time of writing.
