### ISSUE TITLE
Example app and paths

### ISSUE THREAD

**Issue by nasli** [owncloud/ios-sdk#6]
As an _user_ I want be able to review a demo example so I can know the way of use the SDK properly

- [x] Location of the demo example: I will suggest to move it into the root of the project directly instead of inside folder
- [x] as well as all files inside ownCloudSDK. ios-sdk it is already the ownCloudSDK, then you have direct access instead of ios-sdk/ownCloudSDK/ownCloudSDK/
- [x] Use group folders
- [x] Name: Ocean sounds cool but maybe a "SampleApp , Example" sound more understandable and common in SDK's,
- [ ] Features to consider show inside SDK (pending add):
  - [ ] a
  - [ ] b 
  - [ ] ...

**Comment by felix-schwarz** [comment]
As for the location, I'm moving its files to [repo root]/Example in the next commit.
