### ISSUE TITLE
APP Settings

### ISSUE THREAD

**Issue by nasli** [owncloud/ios-sdk#7]
As an _user_ I want be able to change some settings of the app _so_ I can customize some features

- [ ] To discuss, if settings are going to be per account or common to the app, or only some common, where to add in the sdk, bookmark, user
- [ ] Settings:
   - [ ] Security: Passcode
   - [ ] Instant Upload
   - [ ] More..

**Comment by felix-schwarz** [comment]
Thanks for moving this to ios-app issue 3!
