### ISSUE TITLE
Normalized URL supported

### ISSUE THREAD

**Issue by nasli** [owncloud/ios-sdk#9]
As an _user_ I want to be able to enter different types of URL so I can logIn easily

To define

**Comment by felix-schwarz** [comment]
In https://github.com/owncloud/ios-sdk/commit/4c35a72ae5fe15150022f16736206d9017528164, I have implemented an improved version of [ServerURLNormalizer.swift](https://github.com/owncloud/ios/blob/fd8e4114b87e64fb2f50eb1b5973d70eec99826c/Owncloud%20iOs%20Client/Login/Login/ServerURLNormalizer.swift) as [NSURL+OCURLNormalization.m](https://github.com/owncloud/ios-sdk/blob/master/ownCloudSDK/ownCloudSDK/NSURL+OCURLNormalization.m) and show exemplary usage in [RECIPES.md](https://github.com/owncloud/ios-sdk/blob/master/doc/RECIPES.md).

Is there anything left to implement beyond this?

**Comment by felix-schwarz** [comment]
Closing this issue as the API should now cover all cases we discussed last week.
